### ISSUE TITLE
Empty output

### ISSUE THREAD

**Issue by carroarmato0** [r0bj/telegraf-lxc-stats#1]
I've compiled the binary in Ubuntu 16.04 which is running LXC 2.0.0 and LXD 2.0.0

But when I run the command I only get an empty line.

What can I do to help troubleshoot? :)

**Comment by r0bj** [comment]
I've created fresh ubuntu 16.04 installation via vagrant and execute those commands:

```
sudo apt install lxc1
sudo lxc-create -n c1 -t download -- -d ubuntu -r xenial -a amd64
sudo lxc-start -dn c1

sudo ./telegraf-lxc-stats
lxcstats,lxc_host=c1 mem_limit=1040584704,blkio_read_bytes=12288,blkio_write_bytes=4096,mem_usage_perc=1.038382,blkio_writes=1,cpu_time=287158468,mem_usage=10805248,bytes_recv=1374,bytes_sent=1562,blkio_reads=3
```

So it's working with this basic setup.

Binary `telegraf-lxc-stats` needs root privileges to gather LXC stats.
Did you use `sudo` with `telegraf-lxc-stats`?

**Comment by r0bj** [comment]
If you need statistics from LXD containers, please consider different binary: https://github.com/r0bj/telegraf-lxd-stats

**Comment by carroarmato0** [comment]
Oh indeed.  I compiled the lxd binary in a container, but when running the binary I get the following in strace:

> socket(PF_LOCAL, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 9
> setsockopt(9, SOL_SOCKET, SO_BROADCAST, [1], 4) = 0
> connect(9, {sa_family=AF_LOCAL, sun_path="/var/lib/lxd/unix.socket"}, 27) = 0
> epoll_ctl(4, EPOLL_CTL_ADD, 9, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=1913102568, u64=140000667082984}}) = 0
> getsockname(9, {sa_family=AF_LOCAL, NULL}, [2]) = 0
> getpeername(9, {sa_family=AF_LOCAL, sun_path="/var/lib/lxd/unix.socket"}, [27]) = 0
> futex(0xc82002cd08, FUTEX_WAKE, 1)      = 1
> read(9, 0xc820286000, 4096)             = -1 EAGAIN (Resource temporarily unavailable)
> write(9, "GET /1.0/containers/build/state "..., 111) = 111
> futex(0xc82002cd08, FUTEX_WAKE, 1)      = 1
> futex(0x9b8868, FUTEX_WAIT, 0, NULLpanic: interface conversion: interface {} is nil, not map[string]interface {}
> 
> goroutine 68 [running]:
> panic(0x775de0, 0xc820151100)
>   /usr/lib/go-1.6/src/runtime/panic.go:464 +0x3e6
> main.getLxdInterfaceCounters(0xc8200cc9d0, 0x7, 0xc8201f01e0)
>   /root/telegraf-lxd-stats.go:124 +0xdeb
> created by main.gatherApiData
>   /root/telegraf-lxd-stats.go:447 +0xf4
>  <unfinished ...>
> +++ exited with 2 +++

Looks like it's trying to fetch an URL which is not available. Maybe I'm missing something ?

**Comment by r0bj** [comment]
Could you provide output of command for all containers on your host:
`curl -s --unix-socket /var/lib/lxd/unix.socket http:/1.0/containers/<container_name>/state | jq`

**Comment by carroarmato0** [comment]
Here you go:  http://pastebin.com/T2UM7Dn9

**Comment by r0bj** [comment]
I've created version with additional debug messages, could you compile, execute and paste output of that script:
https://gist.github.com/r0bj/746e66abf4736b024f23e90b3c93ed57

**Comment by carroarmato0** [comment]
I now get the following output:

> mysql: {map[memory:map[usage:%!s(float64=0) usage_peak:%!s(float64=0) swap_usage:%!s(float64=0) swap_usage_peak:%!s(float64=0)] network:<nil> pid:%!s(float64=0) processes:%!s(float64=0) status:Stopped status_code:%!s(float64=102) disk:<nil>]}
> panic: interface conversion: interface {} is nil, not map[string]interface {}
> 
> goroutine 86 [running]:
> panic(0x775de0, 0xc820056e00)
>   /usr/lib/go-1.6/src/runtime/panic.go:464 +0x3e6
> main.getLxdInterfaceCounters(0xc8200de210, 0x5, 0xc8201721e0)
>   /root/telegraf-lxd-stats.go:128 +0x10b2
> created by main.gatherApiData
>   /root/telegraf-lxd-stats.go:454 +0xf4

Looks like my  mysql container is making the script choke. I've added the socket output for that container:

https://gist.github.com/carroarmato0/133ba88b19d351ad26bd9a1c7b3c3bce

It seems to be doing that if the container isn't running... I try starting all of them.

**Comment by carroarmato0** [comment]
This is the result after all containers are running:  https://gist.github.com/carroarmato0/9f0bf704aa0772e4fd289f7cfd9d4e5b

As I suspected, something goes wrong with the plugin with shutdown containers

**Comment by r0bj** [comment]
Thanks. I've added proper handling of stopped LXD containers. Please check with current version.

**Comment by carroarmato0** [comment]
Works perfectly! Thanks
