### ISSUE TITLE
Dashboards available?

### ISSUE THREAD

**Issue by damm** [r0bj/telegraf-lxc-stats#2]
Hi,

I was trying to implement this and found myself struggling with the queries so I wondered if you have the dashboards available exported that your screenshots are built from?

Thanks

**Comment by r0bj** [comment]
Unfortunately I didn't put those dashboards anywhere yet. So I pasted dashboard exported to JSON here straight from my grafana. I hope It'll be useful.

[node_overview.json.gz](https://github.com/r0bj/telegraf-lxc-stats/files/531927/node_overview.json.gz)

**Comment by damm** [comment]
Perfect! thanks

**Comment by fajfer** [comment]
Dashboards were really helpful to quickly check if I managed to get telegrafs working correctly :)
